export const ROUTES = {
  SPLASH: 'SPLASH',
  ROOTSTACK: 'ROOTSTACK',
  AUTHSTACK: 'AUTHSTACK',
  MAINSTACK: 'MAINSTACK',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  HOME: 'HOME',
  ADDTASK: 'ADDTASK',
  EDITTASK: 'EDITTASK',
  PROFILE: 'PROFILE',
  INFORMATION: 'INFORMATION',
  SETTING: 'SETTING',
};
